# Generated by Django 2.2.1 on 2019-06-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
