# Generated by Django 2.2.1 on 2019-06-19 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateField()),
                ('team_a', models.CharField(max_length=20)),
                ('team_b', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MatchDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_o_m', models.CharField(max_length=20)),
                ('best_bowling', models.CharField(max_length=20)),
                ('best_batsmen', models.CharField(max_length=20)),
                ('desc', models.TextField()),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tournament.Match')),
            ],
        ),
    ]
