# Generated by Django 2.2.1 on 2019-06-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchdescription',
            name='m_o_m',
            field=models.CharField(default='xyz', max_length=20),
        ),
    ]
