# Generated by Django 2.2.1 on 2019-06-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('skill', models.TextField()),
                ('team', models.CharField(default='-', max_length=100)),
                ('dept', models.CharField(default='-', max_length=100)),
            ],
        ),
    ]
