# Generated by Django 2.2.1 on 2019-06-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='skill',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
