# Generated by Django 2.2.1 on 2019-06-06 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Team', '0002_auto_20190605_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='user_name',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
