# Generated by Django 2.2.1 on 2019-06-06 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0005_auto_20190606_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='user_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
