# Generated by Django 2.2.1 on 2019-06-06 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0006_auto_20190606_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='user_name',
        ),
    ]
